version: "3"
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    env_file: ".env"
    command: pipenv run python3 manage.py runserver
    ports:
      - '8000'
    volumes:
      - .:/app:cached
    depends_on: 
      - redis
  redis:
    image: "redis:latest"
    volumes:
      - "redis_data:/data"
volumes: 
  redis_data:
